#!/bin/bash

###################################### *** CONSTANTS *** #######################################
ext_commerce=(b2badmincockpit b2bapprovalprocess b2bcommerce basecommerce btg btgcockpit commercefacades commerceservices customerreview cybersource hyend2 hygocockpit hygosearch oci payment promotions solrfacetsearch ticketsystem voucher wishlist)
ext_content=(bmecat classificationsystems cms2 cms2lib cmscockpit importcockpit mam mamdemo productcockpit)
ext_channel=(cscockpit mobileoptionals mobileservices print printcockpit reportcockpit)
ext_accelerator=(acceleratorcms acceleratorfacades acceleratorsampledata acceleratorservices b2bacceleratorfacades b2bacceleratorsampledata b2bacceleratorservices)
ext_template=(b2bstore flexstore fulfilmentprocess jmssample soapspring springmvcstore storetemplate yacceleratorcockpits yacceleratorcore yacceleratorfacades yacceleratorinitialdata yacceleratorstorefront yacceleratortest yb2bacceleratorcore yb2bacceleratorfacades yb2bacceleratorinitialdata yb2bacceleratorstorefront yb2bacceleratortest ycockpit ycommercewebservices)
local_extension_path="/home/prabesh/hybris/bin/platform/extensions.xml"
###################################### *** END OF CONSTANTS *** #######################################

#*****************************************************************************************************************
###################################### *** METHODS *** #######################################
### Get the necessary credentials ###
svnCheckout(){
  ### Get the version user wants ###
  echo "Please enter the correct version number of HMS you want to install : "
  read hmsVersionNumber
  echo "Enter your svn username"
  read svnUsername
  echo "Enter your svn password"
  read -s svnPassword
  ### Checkout the code in the folder
  svn checkout https://svn.hybris.de/ebusiness/tags/4.7.5 --username prabesh.shrestha@hybris.com --password $svnPassword
  #svn checkout https://svn.hybris.de/ebusiness/tags/$hmsVersionNumber --username $svnUsername --password $svnPassword
}

loopExtCommerce(){
  echo "Please press y if you want to install the module "
  test="asdf"
  for extCommerce in "${ext_commerce[@]}"
   do
      echo "Install" $extCommerce" ?"
      read install
      if [ "$install" = 'y' ]; then
        echo "You have selected to install".$install
      else
        sed -i '/'.$extCommerce.'/d' $local_extension_path
      fi
      
   done
 }
###################################### *** END OF METHODS *** #######################################

#*****************************************************************************************************************
############## BashScript Starts here #######################
svnCheckout
#loopExtCommerce

#ext_sample_data=(sampledata)
#echo ${ext_commerce[0]}
#echo ${ext_commerce[1]}
### Exit if checkout was not successful 
#if hybrisJiraPlugin*;then 
#  echo "Thank you for the credentials . Checkout was successful"
#else
#  echo "Checkout was not successful. Exiting now ....."
#  exit 0
#fi

###### Ask for the modules to be installed
#echo "I am next command"
echo "Deployment Complete" | mail -s "Automation Script Message" prabesh708@gmail.com
#################### Configuration ####################
