require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DependenciesController do

  # This should return the minimal set of attributes required to create a valid
  # Dependency. As you add validations to Dependency, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DependenciesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dependencies as @dependencies" do
      dependency = Dependency.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dependencies).should eq([dependency])
    end
  end

  describe "GET show" do
    it "assigns the requested dependency as @dependency" do
      dependency = Dependency.create! valid_attributes
      get :show, {:id => dependency.to_param}, valid_session
      assigns(:dependency).should eq(dependency)
    end
  end

  describe "GET new" do
    it "assigns a new dependency as @dependency" do
      get :new, {}, valid_session
      assigns(:dependency).should be_a_new(Dependency)
    end
  end

  describe "GET edit" do
    it "assigns the requested dependency as @dependency" do
      dependency = Dependency.create! valid_attributes
      get :edit, {:id => dependency.to_param}, valid_session
      assigns(:dependency).should eq(dependency)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dependency" do
        expect {
          post :create, {:dependency => valid_attributes}, valid_session
        }.to change(Dependency, :count).by(1)
      end

      it "assigns a newly created dependency as @dependency" do
        post :create, {:dependency => valid_attributes}, valid_session
        assigns(:dependency).should be_a(Dependency)
        assigns(:dependency).should be_persisted
      end

      it "redirects to the created dependency" do
        post :create, {:dependency => valid_attributes}, valid_session
        response.should redirect_to(Dependency.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dependency as @dependency" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dependency.any_instance.stub(:save).and_return(false)
        post :create, {:dependency => {}}, valid_session
        assigns(:dependency).should be_a_new(Dependency)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dependency.any_instance.stub(:save).and_return(false)
        post :create, {:dependency => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dependency" do
        dependency = Dependency.create! valid_attributes
        # Assuming there are no other dependencies in the database, this
        # specifies that the Dependency created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dependency.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dependency.to_param, :dependency => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dependency as @dependency" do
        dependency = Dependency.create! valid_attributes
        put :update, {:id => dependency.to_param, :dependency => valid_attributes}, valid_session
        assigns(:dependency).should eq(dependency)
      end

      it "redirects to the dependency" do
        dependency = Dependency.create! valid_attributes
        put :update, {:id => dependency.to_param, :dependency => valid_attributes}, valid_session
        response.should redirect_to(dependency)
      end
    end

    describe "with invalid params" do
      it "assigns the dependency as @dependency" do
        dependency = Dependency.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dependency.any_instance.stub(:save).and_return(false)
        put :update, {:id => dependency.to_param, :dependency => {}}, valid_session
        assigns(:dependency).should eq(dependency)
      end

      it "re-renders the 'edit' template" do
        dependency = Dependency.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dependency.any_instance.stub(:save).and_return(false)
        put :update, {:id => dependency.to_param, :dependency => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dependency" do
      dependency = Dependency.create! valid_attributes
      expect {
        delete :destroy, {:id => dependency.to_param}, valid_session
      }.to change(Dependency, :count).by(-1)
    end

    it "redirects to the dependencies list" do
      dependency = Dependency.create! valid_attributes
      delete :destroy, {:id => dependency.to_param}, valid_session
      response.should redirect_to(dependencies_url)
    end
  end

end
